# Generated by Django 5.1.7 on 2025-05-04 13:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='Kullanıcı Adı')),
                ('password', models.CharField(max_length=128, verbose_name='Şifre')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-posta')),
                ('first_name', models.CharField(max_length=30, verbose_name='Ad')),
                ('last_name', models.CharField(max_length=30, verbose_name='Soyad')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Yönetici mi?')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Kısa URL')),
                ('content', models.TextField(verbose_name='İçerik')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('status', models.CharField(choices=[('draft', 'Taslak'), ('published', 'Yayınlandı')], default='draft', max_length=10, verbose_name='Durum')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='Yazar')),
            ],
        ),
    ]
